spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_prod
    username: prod_user
    password: prod_pass
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false